### ISSUE TITLE
should Y2 use n2?

### ISSUE THREAD

**Issue by mebrooks** [mintoc/epif#1]
Hi Cóilín, 

I'm looking at the code to try to answer [a question](https://groups.google.com/g/selfisher-users/c/Cr4XsNpeeB0/m/dHqHOm9IAAAJ) about if this model can be fit with `selfisher`. The answer depends on whether there are any shared parameters in the two parts of the model. I'm curious if [this line](https://github.com/mintoc/epif/blob/c394f7e610f211055ee2a6860439f47273960c2c/nested/R/nested_gam.cpp#L88) should have `n2` in the model for `Y2` instead of `n`.  

Best regards,
Mollie

**Comment by mintoc** [comment]
Hi Mollie,

Thanks for checking, I think n is correct as pL is the product of [p1 and p2](https://github.com/mintoc/epif/blob/c394f7e610f211055ee2a6860439f47273960c2c/nested/R/nested_gam.cpp#L84). Using n2 and p2 as in

nll -= sum(dbinom(vector<Type>(Y2.col(0)), n2, p2, true));

would assume conditional independence across the compartments.

Best regards,
Cóilín

**Comment by mebrooks** [comment]
Ah, ok. Thanks. I see they are connected.
